### ISSUE TITLE
Loop in Natalie the writer :)

### ISSUE THREAD

**Issue by meiqimichelle** [TomorrowPartners/tomorrow-web#15]
It is time!

**Comment by meiqimichelle** [comment]
Gaby reached out. Waiting to hear back from Natalie.

**Comment by meiqimichelle** [comment]
Meeting scheduled!

**Comment by meiqimichelle** [comment]
We should send Natalie:
- Access to our working Google Drive folder
- Direct link to the 'impact' content
- Direct link to the case study list/spreadsheet

**Comment by gabybrink** [comment]
Done
