### ISSUE TITLE
Send Natalie what she needs to get started writing

### ISSUE THREAD

**Issue by meiqimichelle** [TomorrowPartners/tomorrow-web#24]
See draft: https://docs.google.com/document/d/1n9WfWGphw48SY2E2usEQdJ63ofnv7J1eCz-zG7a1hyI/edit

Answer all questions except values, which we will brainstorm separately.

**Comment by meiqimichelle** [comment]
Meeting set for Tuesday.

**Comment by aliasamy** [comment]
Done
