### ISSUE TITLE
Visual inspiration research

### ISSUE THREAD

**Issue by meiqimichelle** [TomorrowPartners/tomorrow-web#25]
@danabad is collecting visual inspiration. [more details to come]

**Comment by danabad** [comment]
_Featured Case Study Displays
_Video Display 
_”Carousels”
_Microanimations 
_Full-immersion nav
_Menu transformation w/sroll
_Social Media Integration

**Comment by danabad** [comment]
Complete. Link: https://docs.google.com/a/tomorrowpartners.com/presentation/d/11xHo21h80lWF2dlQALZCq_erqIAalQIztXXQO-RGt7o/edit?usp=sharing

**Comment by meiqimichelle** [comment]
Meeting on Tuesday.

**Comment by meiqimichelle** [comment]
Held the meeting! Done.
