### ISSUE TITLE
Create v1 case study content template

### ISSUE THREAD

**Issue by meiqimichelle** [TomorrowPartners/tomorrow-web#4]
As per our project hypotheses, we think that if we make it easier to collect information for case studies in the first place, we'll be better able to communicate what we do on our site. We think a case studies content template will help with this.

Amy is took a first crack [here](https://docs.google.com/a/tomorrowpartners.com/document/d/1SJj4zXWW1Gm7kdkP1tFwXr5BwUJMmZEs2jaacd7BQzc/edit?usp=sharing).

**Comment by meiqimichelle** [comment]
Sam is testing this with CommonApp to see how it goes.

**Comment by meiqimichelle** [comment]
Note: probably want to loop back with this in another draft after we have more clarity on site direction so that we can target communication goals.

**Comment by meiqimichelle** [comment]
For this task, it is scope to just this first version. Just need to how how it's going.

**Comment by aliasamy** [comment]
Checked with Sam, she will give feedback once she is done

**Comment by meiqimichelle** [comment]
Sam went through the template once. She asked that we look at it and see if it makes it clear when the project did.

**Comment by aliasamy** [comment]
Sam's answers here: https://docs.google.com/document/d/1wJY_pGw4DjDGgk73n8QdaGQLyZwvwN7ZhLita8f-J4s/edit

**Comment by meiqimichelle** [comment]
Next step: a few more eyes should look at Sam's answers and see if our template gives us enough fodder, or the fodder we were hoping for, to create a case study (at least, at this point -- will probably change as we get more direction on the overall communications goals of the site).

**Comment by meiqimichelle** [comment]
Closing this issue, as there is a new one #13 for Gaby's review and next steps.
