### ISSUE TITLE
First draft of content

### ISSUE THREAD

**Issue by meiqimichelle** [TomorrowPartners/tomorrow-web#6]
Filter content through the two lenses we've already identified.

This can just be in a Google doc.

Two directions:
Direction 1: customer-centric / partnership
Direction 2: spectrum / thinking needs making

/cc @bbreuner

**Comment by aliasamy** [comment]
Created new doc here https://docs.google.com/document/d/1q7xW9cDkjgN9PB4S_T0cG2szixjliL8q1127kuXAgWM/edit

**Comment by meiqimichelle** [comment]
Update (and let's test the new GH integration with Slack): I chatted with Amy about her doc, and we decided to divide and conquer going forward. She's taking the first direction and having a crack at pulling relevant content from the existing website and other materials (slides decks, etc), and I'm forking her work and getting started with the second direction.
